

import InputField from "@/components/InputElements/InputField";
import OTPField from "@/components/InputElements/OTPField";
import PasswordField from "@/components/InputElements/PasswordField";
import styles from "@/styles/Home.module.css";
import { Form } from "antd";
import { Geist, Geist_Mono } from "next/font/google";
import Head from "next/head";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>





          <div className={styles.intro}>
            <Form layout="vertical">
              <InputField name="name" label="Name" maxLength={50} showCount />

              <PasswordField name="password" label="Password" />

              <OTPField name="otp" label="Enter OTP" length={6} />
            </Form>
          </div>




          <div className={styles.ctas}>
            <a
              className={styles.primary}
              href="/biodata"
              rel="noopener noreferrer"
            >
              <Image
                className={styles.logo}
                src="/vercel.svg"
                alt="Vercel logomark"
                width={16}
                height={16}
              />
              Biodata
            </a>

          </div>
        </main>
      </div>
    </>
  );
}
